version: "3"

services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    expose:
      - 9411
    labels:
      org.label-schema.group: "monitoring"

  prometheus:
    image: prom/prometheus:v2.34.0
    volumes:
      - ./docker/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    ports:
      - 9090:9090
    expose:
      - 9090
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    labels:
      org.label-schema.group: "monitoring"

  discovery:
    build: platform-services/discovery/target
    ports:
    - 8761:8761
    environment:
      - LABEL_GROUP=platform-services
      - LABEL_ID=discovery
      - LABEL_DESCRIPTION=Discovery
      - JAR_NAME_TO_RUN=app.jar
      - PORT_TO_EXPOSE=8761

  apigateway:
    build: platform-services/apigateway/target
    ports:
      - 8080:8080
    environment:
      - LABEL_GROUP=platform-services
      - LABEL_ID=apigateway
      - LABEL_DESCRIPTION=API Gateway
      - JAR_NAME_TO_RUN=app.jar
      - PORT_TO_EXPOSE=8080

  common:
    build: business-services/common/target
    volumes:
      - ~/cloud-git-repo:/cloud-git-repo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health/ping"]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      - LABEL_GROUP=business-services
      - LABEL_ID=common
      - LABEL_DESCRIPTION=Common service (config, etc.)
      - JAR_NAME_TO_RUN=app.jar
      - PORT_TO_EXPOSE=8888

  one:
    restart: on-failure
    build: business-services/one/target
    entrypoint: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/app.jar"]
    ports:
      - 5005:5005
    depends_on:
      - apigateway
      - discovery
      - common
      - two
#    deploy:
#      mode: replicated
#      replicas: 2
    environment:
      - LABEL_GROUP=business-services
      - LABEL_ID=one
      - LABEL_DESCRIPTION=One service
      - JAR_NAME_TO_RUN=app1.jar
      - PORT_TO_EXPOSE=62805

  two:
    restart: on-failure
    build: business-services/two/target
    depends_on:
      - apigateway
      - discovery
      - common
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - LABEL_GROUP=business-services
      - LABEL_ID=two
      - LABEL_DESCRIPTION=Two service
      - JAR_NAME_TO_RUN=app.jar
      - PORT_TO_EXPOSE=62806

  two-api:
    restart: on-failure
    build: business-services/two-api/target
    depends_on:
      - apigateway
      - discovery
      - common
    environment:
      - LABEL_GROUP=business-services
      - LABEL_ID=two-api
      - LABEL_DESCRIPTION=Two-api service
      - JAR_NAME_TO_RUN=app.jar
      - PORT_TO_EXPOSE=62807