global:
  scrape_interval:     15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus' # Job to scrape Prometheus metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'eureka'
    eureka_sd_configs:
      - server: 'http://discovery:8761/eureka'
    relabel_configs:
        #Path to rewrite metrics
      - source_labels: [ "__meta_eureka_app_instance_metadata_prometheus_path" ]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
        #Add a custom label sys_ Its value is obtained from the configuration Eureka
      - source_labels: [ "__meta_eureka_app_instance_metadata_sys_module" ]
        action: replace
        target_label: sys_module
        regex: (.+)
        #Override management port
      - source_labels: [ __address__, __meta_eureka_app_instance_metadata_prometheus_port ]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__