eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery:8761/eureka}
  instance:
    preferIpAddress: true
    metadata-map:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
      "prometheus.port": "${management.server.port}"
      "sys.module": "two-service"